// Auto-generated by scripts/generate-build-info.mjs
export const BUILD_INFO = Object.freeze({
  buildUtc: "1970-01-01T00:00:00.000Z",
  gitCommitSha: "unknown",
  gitCommitRef: "unknown",
  vercelEnv: "unknown",
  vercelProjectProductionUrl: null
});
